### ISSUE TITLE
Minor error in day 21

### ISSUE THREAD

**Issue by beanz** [p88h/aoc2024#1]
https://github.com/p88h/aoc2024/blob/6b748e909b4fbfda928285b0720a4625a6fe2134/src/day21.zig#L141

This should be:

     '6' => &.{">A"},

because 5 is immediately adjacent to 6.

**Comment by beanz** [comment]
The 8 to 5 sequence is wrong too.

**Comment by p88h** [comment]
Thanks! 
I apparently did not have these moves in my inputs ... and never did get around to do a full verification after submitting a correct answer.
Fixed in ebb68c0

**Comment by p88h** [comment]
resolved
